### ISSUE TITLE
Realizar la planificación concluyendo la it0

### ISSUE THREAD

**Issue by RedBed24** [RedBed24/ISO2-2023-B05#10]
Partiendo de la primera aproximación realizada por @antoniocg73 y @NoeliaOwo, en la última reunión determinamos que sería necesario que todos nos centremos en simplificar el problema y elegir una priorización de CDU y establecer unas iteraciones concretas.
También será necesario estimar un tiempo de trabajo para cada disciplina e iteraciones.

- [x] Confirmar el análisis de RF y su mappeo a CDU
- [x] Confirmar la priorización de CDU
- [x] Elegir grupos funcionales si procede
- [x] Establecer Iteraciones
- [x] Estimar tiempos de trabajo por disciplina e Iteración y hacer el calendario

**Comment by NoeliaOwo** [comment]
Estimación del tiempo de trabajo por disciplina e iteración y calendario terminado :) salu2 de natalia noelia
