### ISSUE TITLE
Juntar en grupos funcionales las Iteraciones

### ISSUE THREAD

**Issue by RedBed24** [RedBed24/ISO2-2023-B05#11]
Tras hacer una primera aproximación de las horas, para cada disciplina y caso de uso, se decició juntar en casos funcionales aquellos casos de uso cliente-servidor.
Ahora toca actualizar el excel de tal forma que las horas de estos casos de uso se sumen en una iteración.

**Comment by antoniocg73** [comment]
Tabla de iteraciones completa realizada.

**Comment by RedBed24** [comment]
No se ha puesto el enlace correctamente
