### ISSUE TITLE
Aprender sobre JUnit.

### ISSUE THREAD

**Issue by RedBed24** [RedBed24/ISO2-2023-B05#22]
Para realizar las pruebas del software se usará JUnit, esta tarea queda para los testers, que deben aprender sobre esta tecnología.

**Comment by Lunao01** [comment]
Se ha estudiado JUnit y realizado una documentación explicando los aspectos que se llevarán a cabo durante el testing y el funcionamiento de la herramienta. Esta ha sido compartida con el resto de los integrantes del proyecto.
