### ISSUE TITLE
Análisis de requisitos y mappeo de Casos De Uso

### ISSUE THREAD

**Issue by RedBed24** [RedBed24/ISO2-2023-B05#6]
Para seguir con el sistema, primero debemos:

- [x] #7
- [x] Crear un catálogo de requisitos para cada sistema
- [x] Mapear requisitos a CDU
- [x] Establecer una prioridad para cada CDU
- [x] Mapear CDU a iteraciones

**Comment by antoniocg73** [comment]
Terminado y pull request hecho con el word
